import { execSync } from "child_process";
import { writeFileSync, chmodSync, existsSync, mkdirSync } from "fs";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(__dirname, "../../");
const hooksDir = resolve(repoRoot, ".git/hooks");

if (!existsSync(hooksDir)) {
  mkdirSync(hooksDir, { recursive: true });
}

const hookPath = resolve(hooksDir, "post-commit");

const hookScript = `#!/bin/sh
# Auto-generated by setup-hooks — pushes every commit to GitHub automatically.
# Runs in the background so it never blocks the commit itself.

if [ -z "$GITHUB_TOKEN" ] || [ -z "$GITHUB_REPO_URL" ]; then
  echo "[github-sync] GITHUB_TOKEN or GITHUB_REPO_URL not set — skipping."
  exit 0
fi

(
  REPO_URL_WITH_TOKEN=$(echo "$GITHUB_REPO_URL" | sed "s|https://|https://$GITHUB_TOKEN@|")
  git remote set-url github "$REPO_URL_WITH_TOKEN" 2>/dev/null || git remote add github "$REPO_URL_WITH_TOKEN" 2>/dev/null
  BRANCH=$(git rev-parse --abbrev-ref HEAD 2>/dev/null)
  git push github "$BRANCH" --follow-tags --quiet 2>&1 | sed 's/^/[github-sync] /'
) &
`;

writeFileSync(hookPath, hookScript, { encoding: "utf-8" });
chmodSync(hookPath, 0o755);

console.log(`post-commit hook installed at ${hookPath}`);
console.log("Every future commit will be pushed to GitHub automatically.");
